### PR TITLE
delete cookiejar folder when failing to load

### PR DESCRIPTION
**Pull request by Bart274**
this will enable us to update the component in homeassistant

### CODE REVIEW

**Comment by torarnv** [comment]
Why is this needed? We already detect the failed load and ignore it, and the new cookiejar will then overwrite the old one?

**Comment by Bart274** [comment]
I don't think this is true, as long as the old wrong one isn't deleted, it keeps trying to load this file and the pyicloud service fails to load in HA

**Comment by torarnv** [comment]
That's not what I'm observing here.
With https://gist.github.com/torarnv/f0e47d0a70c6f1afc48a81dc51c06fd2 applied, I'm seeing:

```
[INFO] icloudphotobackup: Logging into iCloud as 'asdasd...
[WARNING] pyicloud.base: Failed to read cookiejar
[INFO] pyicloud.base: Authenticating as asdasd
[INFO] pyicloud.base: Cookies saved
[INFO] pyicloud.base: Authentication completed successfully
```

Try adding the same logging. Once login is successful we overwrite the original cookiejar.

**Comment by Bart274** [comment]
I talked to you about this on Gitter.
When we try to use the current version we can get these errors:
```
16-03-13 11:57:53 homeassistant.bootstrap: Error during setup of component icloud
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\homeassistant-0.15.0.dev0-py3.4.egg\homeassistant\bootstrap.py", line 105, in _setup_component
    if not component.setup(hass, config):
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\custom_components\icloud.py", line 82, in setup
    ignored_devices)
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\custom_components\icloud.py", line 421, in __init__
    verify=True)
  File "C:\Users\Bart\AppData\Roaming\.homeassistant\lib\pyicloud\base.py", line 152, in __init__
    self.session.cookies.load()
  File "C:\Python34\lib\http\cookiejar.py", line 1765, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "C:\Python34\lib\http\cookiejar.py", line 1864, in _really_load
    magic = f.readline()
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 41: character maps to <undefined>
```
the only way to fix this now is to manually delete the cookiejar folder and then HA can load pyicloud

**Comment by torarnv** [comment]
Ah, then the right fix is to catch UnicodeDecodeError as well, I'll land a fix for that, thanks!

**Comment by Bart274** [comment]
you're welcome :)
can you push a new release for this on pypi as well so we can finally update the component in HA?

**Comment by torarnv** [comment]
Done. https://pypi.python.org/pypi/pyicloud/0.8.3

**Pull request closed without merging**
