### PR TITLE
Handle HTTP errors before trying to parse JSON

### PR DESCRIPTION
**Pull request by torarnv**

### CODE REVIEW

**Comment by mjj4791** [comment]
@torarnv 
This fix seems to help; I can now catch the exception when I get a http-450 response.
However you need to do one change for your change to work:

Change this definition:

    def _raise_error(code, reason):

into:

    def _raise_error(self, code, reason):

**Comment by torarnv** [comment]
@mjj4791 all good?

**Comment by mjj4791** [comment]
@torarnv 
I manually added the changes before; which seemed to work fine
After that I uograded homeassistant and the patch got lost in the upgrade...

Just replaced base.py with this version again...

I usually see the error every 30 minutes, will let you know the results

**Comment by mjj4791** [comment]
This fix seems to work; I still get an error, about every 30 minutes; but now it is a sensible exception that is catchable....

```
  File "/home/hass/.homeassistant/deps/pyicloud/base.py", line 276, in devices
    self.params
  File "/home/hass/.homeassistant/deps/pyicloud/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "/home/hass/.homeassistant/deps/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
  File "/srv/hass/lib/python3.4/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/hass/.homeassistant/deps/pyicloud/base.py", line 70, in request
    self._raise_error(response.status_code, response.reason)
  File "/home/hass/.homeassistant/deps/pyicloud/base.py", line 107, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError:  (450)

```

**Pull request merged**
