### PR TITLE
Added working delete function for photos

### LINKED ISSUE #239: Is there any way to delete photo?
is there any way to delete photo?

### PR DESCRIPTION
**Pull request by r3ticuli**
Added working delete function for CPLAssets.

Fixes #239

### CODE REVIEW

**Comment by Tatsh** [comment]
Would definitely like to see this merged. Fix the long lines:

```
pyicloud/services/photos.py:508:80: E501 line too long (266 > 79 characters)
pyicloud/services/photos.py:510:80: E501 line too long (82 > 79 characters)
```

**Comment by Tatsh** [comment]
Also, consider making a way to batch delete. I've been posting with 100 operations at a time with no issue but I figure if you sent thousands of HTTP requests for only 1 operation that's very inefficient and the API will throttle a lot more. Perhaps like a `add_to_delete_queue()` method (or put this on the service and accept an asset argument) and the photos service would have a deletion queue list. On the service object you could call `delete_all_in_queue()` or something like that. In that method, make it delete only 100 at a time.

**Comment by Tatsh** [comment]
For permanent deletion, use `"fields":{"isExpunged":{"value":1}}}}]`. Maybe accept `permanent` as a kwarg? Otherwise an `expunge()` method.

**Comment by jrmlhermitte** [comment]
worked great for me. can we merge this in soon? @r3ticuli any progress?
we can add more features to it later perhaps?

**Comment by r3ticuli** [comment]
I’ll fix this in the coming hours. And agreed - we can add more to it later.

**Comment by r3ticuli** [comment]
done! waiting for review now.

**Comment by Aadit-Bhojgi** [comment]
Is this delete function working? @r3ticuli

**Comment by chadj** [comment]
@torarnv this gets a +1 from me

**Comment by jrmlhermitte** [comment]
:+1: from a user 
I deleted all my icloud photos using this:
```python
photos_iter = iter(api.photos.all)
for i, photo in enumerate(photos_iter):
    print(f"Deleting file {photo.filename}")
    photo.delete()
```
I think I had to run it a few times (because not all files were deleted, probably an apple side bug).
But helped me become apple-free. thanks!

**Pull request merged**
