### PR TITLE
Fix 450 error

### LINKED ISSUE #156: api.devices leads to PyiCloudAPIResponseError:  (450)
Hi,
I am running macOS Sierra and python 3. Trying to read my devices as described in the readme leads to an Error.

>> api.devices

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/pyicloud-master/pyicloud/base.py", line 297, in devices
    self.params
  File "/Applications/pyicloud-master/pyicloud/services/findmyiphone.py", line 28, in __init__
    self.refresh_client()
  File "/Applications/pyicloud-master/pyicloud/services/findmyiphone.py", line 44, in refresh_client
    'selectedDevice': 'all',
  File "/usr/local/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Applications/pyicloud-master/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/Applications/pyicloud-master/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError:  (450)

### PR DESCRIPTION
**Pull request by Quentame**
- while refreshing client after 20 min of non request

Fixes #156

### CODE REVIEW

**Comment by reedriley** [comment]
I patched this diff locally to try it out (from within Home Assistant).  My logs now show retry attempts when I encounter error 450, so that's great!

But then after several hours I see this error in the logs:
```
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <REDACTED> for icloud
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: <REDACTED> (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f849c7b9150>: Failed to establish a new connection: [Errno -3] Try again'))
  File "/usr/src/homeassistant/homeassistant/components/icloud/__init__.py", line 124, in async_setup_entry
  File "/usr/src/homeassistant/homeassistant/components/icloud/account.py", line 100, in setup
    self._username, self._password, self._icloud_dir.path
  File "/usr/local/lib/python3.7/site-packages/pyicloud/base.py", line 203, in __init__
  File "/usr/local/lib/python3.7/site-packages/pyicloud/base.py", line 222, in authenticate
  File "/usr/local/lib/python3.7/site-packages/pyicloud/base.py", line 69, in request
```

After this error happens; I no longer see any further attempts to authenticate; no `[pyicloud.services.findmyiphone.http]  (450). Retrying ...` lines, no successes and no failures.

Restarting Home Assistant fixes things.  I suspect there are maybe two necessary bugfixes here; the first in pyicloud involving `MaxRetryError` and also in Home Assistant if there's any error handling you'd recommend be added to the icloud component.

**Comment by Quentame** [comment]
Hi @reedriley !

Thanks a lot for testing.

I think this gonna be fixed by #227.

Now that I am aware I'll tests better with your test case.

Actually fixing a lot of things in iCloud in HA.

**Comment by reedriley** [comment]
In that case, I'll patch #227 locally as well and let you know if anything breaks.  😁

**Comment by Quentame** [comment]
It breaks everything inside HA, you need https://github.com/Quentame/home-assistant/tree/icloud/fmi_reduce_battery_usage

**Pull request merged**
