### PR TITLE
added new function to calendars

### PR DESCRIPTION
**Pull request by maciejbuchert**
I added function that return calendars - names, guid, url and more

### CODE REVIEW

**Comment by maciejbuchert** [comment]
https://github.com/picklepete/pyicloud/issues/15

**Comment by maciejbuchert** [comment]
What is wrong?

**Comment by coddingtonbear** [comment]
@maciejbuchert -- if you click on the red X next to your last commit, it'll bring you to a build report showing you what errors were encountered while our buildbot attempted to test your changes.  It looks like you'll need to push up a fix for that before we can look at merging your changes.  Let me know if you have any questions, though!

**Comment by gieljnssns** [comment]
Any updates on this?

**Comment by maciejbuchert** [comment]
As you can see, no 😕

**Comment by coddingtonbear** [comment]
Sorry, you all -- contributors aren't automatically notified by Github when build problems like this are resolved, and none of us have the time to open all of our many projects' pull requests to see if they're actionable.  I should've told you to comment when you'd resolved them, though; sorry about that!  I'm sure one of us will have a look at this sometime soon, now that we know it's ready for another glance.

**Comment by coddingtonbear** [comment]
Looks good to me, @maciejbuchert -- thanks for taking the time to file a PR, and sorry about the delay!

**Pull request merged**
