### PR TITLE
Add timezone using tzlocal

### PR DESCRIPTION
**Pull request by Bart274**
If the current code fails, the timezone will be added using tzlocal

### CODE REVIEW

**Comment by torarnv** [comment]
Is there any reason the keep the current code?

Please squash the three commits into one.

**Comment by Bart274** [comment]
I kept the original code so it wouldn't break anything for other users if it worked for them before. :)
If you think we can remove it and just use the tzlocal method, I can change it?


I haven't used github a lot so I don't know how to squash these commits into one commit. I'll take a look at it on monday! :)

**Comment by torarnv** [comment]
If the module provides the required functionality then we can safely remove the old code. I'll have to verify that we can use the module first, will do that when I get home.

Don't worry about the squashing, I can do that for you.

**Comment by Bart274** [comment]
Thanks! That would be helpful! :)

**Comment by torarnv** [comment]
Fixed in a6aa998a04958, thanks!

**Pull request closed without merging**
