### PR TITLE
Allow zero-sized files on Drive

### PR DESCRIPTION
**Pull request by ixs**
The webinterface to drive claims, that zero sized files are not supported
on Drive.

Uploading one seems to work however with the only caveat that no receipt
is returned. Handle this case by only adding receipt if available to the
_update_contentws() call.
This allows for feature parity with the bird/cloudd synced drive, which does
zero sized files.

Drive-By: Add a get_app_data() call to the Drive module. This seems to be
a replacement for ubiquity which seems to be deprecated.

### CODE REVIEW

**Comment by Quentame** [comment]
So this will fix #282 and #197 ?

**Comment by ixs** [comment]
@Quentame No. It will not fix those problems yet. I believe - keyword being believe - that ubiquityws is basically gone. I am just not sure where the data went instead. I need to do more digging but reverse engineering cloudd is not that easy unfortunately.

The App Library call is just a single thing that _might_ be a first step in developing the api.files replacement.

BTW: Are you on IRC? Easier to talk there...

**Comment by Quentame** [comment]
Oh, okeyyy.

Nope but Discord Quentame#7196 , Messenger or WhatsApp.

Thanks for all your work !

**Comment by ixs** [comment]
@Quentame alright, you got a request on discord from ixs#1677.

The FUSE driver is done btw... It's not perfect yet, but it works: https://github.com/ixs/iCloudDriveFuse

**Pull request merged**
