### PR TITLE
Simplify login sequence

### PR DESCRIPTION
**Pull request by torarnv**

### CODE REVIEW

**Comment by torarnv** [comment]
@picklepete Does the last commit (c3176fa) make sense to you?

**Comment by picklepete** [comment]
@torarnv Hey - sorry for the delayed response. At first glance it looks good, nice work!

**Comment by torarnv** [comment]
@picklepete Thanks! Do you remember why the `id` was needed?

**Comment by coddingtonbear** [comment]
Awesome; thanks @tornrv!

**Pull request merged**
