### PR TITLE
Reimplement PhotosService to use the new ckdatabasews back-end

### PR DESCRIPTION
**Pull request by chadj**
Here's a pull request to merge in changes discussed in picklepete/pyicloud#136.  With the current released version of pyicloud being broken I figured it was best to get this discussion started.

### CODE REVIEW

**Comment by torarnv** [comment]
Nice work! And good timing, I haven't had time to work much on this lately 😃 

Are the things listed in #136 the only behavioral changes or are there any more things to be aware of?

**Comment by chadj** [comment]
Yeah, my comments in #136 are pretty comprehensive.   I'm nearly positive that covers everything.

**Comment by chadj** [comment]
Ok, I resolved the conflict in this pull request that resulted from be3d447c002a149da1f29e71ae55f03ee9ed224a.  One note, in  https://github.com/chadj/pyicloud/blob/ckdatabasews/pyicloud/base.py#L73, there are times when the server returns useful information in the response as json even though a 200 Response code was not returned.  So if the response was not OK but json was returned don't short circuit out of response handling.

**Comment by bobhavlin** [comment]
Trying to install this commit to get photos working again - what am I doing wrong?

pip install git+https://github.com/picklepete/pyicloud.git@67504f9b4e476f43a97a8d2192d033519ebfc497

Collecting git+https://github.com/picklepete/pyicloud.git@67504f9b4e476f43a97a8d2192d033519ebfc497
  Cloning https://github.com/picklepete/pyicloud.git (to 67504f9b4e476f43a97a8d2192d033519ebfc497) to /tmp/pip-rCCaXY-build
  Could not find a tag or branch '67504f9b4e476f43a97a8d2192d033519ebfc497', assuming commit.
fatal: reference is not a tree: 67504f9b4e476f43a97a8d2192d033519ebfc497
Command "git checkout -q 67504f9b4e476f43a97a8d2192d033519ebfc497" failed with error code 128 in /tmp/pip-rCCaXY-build

**Comment by coddingtonbear** [comment]
@bobhavlin -- that specific commit isn't (yet?) in this repo -- you'll need to clone it from @chadj's fork.  The requirement line would be something like `pip install git+https://github.com/chadj/pyicloud.git@67504f9b4e476f43a97a8d2192d033519ebfc497`

**Comment by chadj** [comment]
Probably the easiest way to try out that branch is installing with:

```
$ pip uninstall pyicloud
$ pip install git+https://github.com/chadj/pyicloud.git@ckdatabasews
```

**Comment by ajlyakhov** [comment]
Hi @chadj ,
thank you for your commit, I just give it a try but got this error (during an attempt to access api.photos.all):

`pyicloud.exceptions.PyiCloudServiceNotActivatedErrror: Please log into https://icloud.com/ to manually finish setting up your iCloud service (ZONE_NOT_FOUND)`

What this error message actually mean?

**Comment by chadj** [comment]
@ajlyakhov Are you able to login to icloud.com (with a browser) and access your photos library?  This error normally occurs when the icloud acount in question either isn't done being setup or has no photo library.

**Comment by armoza** [comment]
Hey guys,

Any updates on merging this back to the master?

Thanks!

**Pull request merged**
