### PR TITLE
Release v1.10.1

### PR DESCRIPTION
**Pull request by nzapponi**
Ready to release `v0.10.1`, which includes 2FA support among other things.

### CODE REVIEW

**Comment by nzapponi** [comment]
@picklepete could you please grant me access on PyPI so that I can push the new version up?
My username is nzapponi.

Thanks!

**Comment by nzapponi** [comment]
Closes #102

**Comment by gcobb321** [comment]
Congrats on everything you have done to spearhead this important update. It was a pleasure working with you over the past few months getting everything ready for the release. I appreciate the opportunity to be able to provide a production testing platform and to offer a few suggestions along the way. FYI - The iCloud3 variant released 3 weeks ago has been downloaded over 600 times with no issues so you can be sure the code is solid. 

I’m sure your plan now is to put your feet up and relax a bit. Good luck with doing that.

**Comment by nzapponi** [comment]
Thanks for all the help @gcobb321 !

**Comment by gcobb321** [comment]
Niccolo,
I hope things are going well.

I am in the process of restructuring iCloud3 from top-to-bottom to reduce it's size, make it more modular, remove dead code, improve it's performance and add a number of features. That has lead me into the customized version of Pyicloud I am using to reduce the calls to Apple servers and to make the data I need easier to retrieve.

One of the areas I am trying to implement is retrieving a single device's location information rather than the location of all of the devices in the Family Sharing List that is implemented in the FindMyiPhoneServiceManager and the way it's always been. What I'm doing is:
    1. I do the initial 'devices' call with 'with_family=True' when first setting up Pyicloud and get the complete list of devices in the FamShr list, which is good. 
    2. After that, If I do a 'refresh_client' to update the location with the 'with_family=True' I get the location of all of the devices (the way it has always worked and the way I have implemented it in iCloud3).
    3. If I use 'with_family=False', only the devices associated with the iCloud account owner are returned. This happens if I use 'selectedDevice="all"' or 'selectedDevice=[device_id]'. 

The result is the other devices in the FamShr list can not be returned unless 'with_family=True'.

Have you implemented, heard about, seen, figured out or can provide any hints on whether this is possible or not possible, and if possible, where I might be able to go to only get the location for a single device. It might be through another parameter, a different webhook end point or something else.

Thanks in advance.

Gary Cobb
@gcobb321

**Comment by nzapponi** [comment]
HI @gcobb321 , to be honest I haven't really tried... And I kind of gave up on the whole iCloud integration idea: it keeps breaking for me and it's more of a pain than it's worth!

**Comment by gcobb321** [comment]
Understand. I'll pass along anything I discover.

------ Original Message ------
From: "Niccolo Zapponi" ***@***.***>
To: "picklepete/pyicloud" ***@***.***>
Cc: "Gary Cobb" ***@***.***>; "Mention" 
***@***.***>
Sent: 6/16/2021 1:24:42 AM
Subject: Re: [picklepete/pyicloud] Release v0.10.1 (#321)

**Comment by marc965** [comment]
Hi!
I am using pyicloud 0.10.2 with Python 3.7.3 on Rasbian.
I am polling the latitude and longitude all five minutes and all is working very well.
Unfortunately the 2FA is lasting for only 24h.

Any suggestions?

**Pull request merged**
